name: Main - CurseForge - Package and Release - All pushes

# Deploy on all pushes to master, except '.github/**' folder.
on:
  push:
    branches:
      - master
    tags:
      - '*'
      - '!**-alpha**'
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:

  build-and-publish:
  
    if: "!contains(github.event.head_commit.message, 'update changelog')"
    runs-on: ubuntu-latest
    
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # "GITHUB_TOKEN" is a secret always provided to the workflow
                                                 # for your own token, the name cannot start with "GITHUB_"


    steps:
    
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for automated history and tags

      - name: Hack around https://github.com/actions/checkout/issues/290
        run: |
          git fetch --tags --force

      - uses: leafo/gh-actions-lua@v10.0.0

      - name: Create Changelog
        run: lua Plater_ChangeLog.lua latest >> CHANGELOG.md

      - name: Package and Release
        uses: BigWigsMods/packager@master
        #continue-on-error: true
        with:
          args: -S -o -n "{project-version}:{project-version}"